//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_420_Osipov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerStats
    {
        public int IDPlayer { get; set; }
        public Nullable<int> NumOfMatches { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Loses { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
