//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_420_Osipov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.MatchPlayers = new HashSet<MatchPlayers>();
            this.TeamsHistory = new HashSet<TeamsHistory>();
        }
    
        public int IDPlayer { get; set; }
        public string Nickname { get; set; }
        public string Phone { get; set; }
        public Nullable<int> IDRole { get; set; }
        public Nullable<int> IDTeam { get; set; }
        public Nullable<int> IDUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchPlayers> MatchPlayers { get; set; }
        public virtual Role Role { get; set; }
        public virtual PlayerStats PlayerStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamsHistory> TeamsHistory { get; set; }
        public virtual User User { get; set; }
    }
}
