//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_420_Osipov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamsHistory
    {
        public int IDHistory { get; set; }
        public Nullable<int> IDPlayer { get; set; }
        public Nullable<int> IDTeam { get; set; }
        public string JoinDate { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Team Team { get; set; }
    }
}
