//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_420_Osipov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentApplication
    {
        public int IDTournamentApps { get; set; }
        public Nullable<int> IDUser { get; set; }
        public string People { get; set; }
        public string UserPreferredRole { get; set; }
        public Nullable<int> IDTournament { get; set; }
    
        public virtual Tournament Tournament { get; set; }
        public virtual User User { get; set; }
    }
}
